version: "3.8"

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "1m"
    max-file: "10"

x-resources: &default-resources
  limits:
    cpus: "1.5"
    memory: 500M

services:
  camera-server:
    container_name: "camera-server"
    build:
      context: /home/ubuntu/workspace/remote-opencv-streaming-live-video
      dockerfile: Dockerfile
    image: camera-server:v1
    restart: unless-stopped
    ports:
      - 800:800
      - 5000:5000
    deploy:
      resources: *default-resources
    logging: *default-logging